AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Serverless Application

  Sample SAM Template for AWS Serverless Application

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  InstanceScheduler:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: scheduler/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        InstanceTimer:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
      Tags:
        Owner: jdalrymplehamilton
        Description: This lambda will scan all EC2 and RDS instances for shutdown / startup tags on 5 minute intervals.
        Name: StartupShutdownScheduler
        Project: SmartPlanning
      Policies:
        - AWSLambdaBasicExecutionRole # Managed Policy
        - Version: '2012-10-17'
          Statement:
            - Sid: startstopec2
              Effect: Allow
              Action:
                - ec2:StartInstances
                - ec2:StopInstances
                - ec2:DescribeRegions
                - ec2:DescribeInstances
              Resource: "*"
        - Version: '2012-10-17'
          Statement:
            - Sid: startstoprds
              Effect: Allow
              Action:
                - rds:StopDBInstance
                - rds:StartDBInstance
                - rds:DescribeDBInstances
                - rds:ListTagsForResource
              Resource: "*"
    Tags:
      Owner: jdalrymplehamilton
      Description: This lambda will scan all EC2 and RDS instances for shutdown / startup tags on 5 minute intervals.
      Name: StartupShutdownScheduler
      Project: SmartPlanning

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  InstanceScheduler:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt InstanceScheduler.Arn
  InstanceSchedulerIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt InstanceSchedulerRole.Arn
